<!DOCTYPE html>
<html>
<head>
<title>My page</title>
</head>
<body>
<!-- This is HTML comment -->

<?php
$var; $_var; $Var; // Valid variable names
//$123var; $456; $my-test; // Not valid
?>

<?php
// Declaration
$foo = "hello";
$bar = 12;
// Concatenation
$boom = $foo . $bar; // $boom equals "hello12"
$baz = $foo . "world"; // $baz equals "helloworld"
// Destruction
unset($foo); // $foo doesn’t exist anymore
?>

<p>
Hello World ! <br/>
<?php
$var = 'PHP.';
echo "This sentence was generated by " . $var;
?>
</p>
</body>
</html>